### ISSUE TITLE
update dependencies and resolve Dependabot alerts

### ISSUE THREAD

**Issue by peterstadler** [Edirom/vife-meigarage-webclient#19]
there's a long list at  https://github.com/Edirom/vife-meigarage-webclient/security/dependabot that should be addressed, IMHO.

Who feels responsible and could tackle this? @anneferger , @kepper ?!

**Comment by anneferger** [comment]
I feel responsible, thanks for the reminder!

**Comment by anneferger** [comment]
Remaining security issues need big upgrades, currently working on them, but will probably still take some time

**Comment by anneferger** [comment]
https://github.com/Edirom/vife-meigarage-webclient/commit/275efb414f185490c1149afe88afaeafd984b8f0
Shiny new version without any alerts will be version 1.0.0

**Comment by anneferger** [comment]
https://github.com/Edirom/vife-meigarage-webclient/releases/tag/v1.0.0
