### ISSUE TITLE
Broken link to API

### ISSUE THREAD

**Issue by daniel-jettka** [Edirom/vife-meigarage-webclient#258]
At the bottom of the page there is a link to "API" - https://meigarage.edirom.de/
-> works here (https://meigarage.edirom.de/ege-webservice/)

But on subpages it does not work, e.g. https://meigarage.edirom.de/conversions/mei30/mei40
-> not working here (https://meigarage.edirom.de/conversions/ege-webservice/)

**Comment by anneferger** [comment]
Moved to frontend repository since this is a frontend issue

**Comment by anneferger** [comment]
Fixed in 3fdf1ad

**Comment by anneferger** [comment]
Thank you for finding and reporting this issue, can you recheck if it works now? Works on https://meigarage.edirom.de/conversions/mei30/mei40 for me now.
